[package]
name = "sdl"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
cstr = "0.2"
num-traits = "0.2.14"
once_cell = "1.8.0"
sdl-sys = { path = "../sdl-sys" }
thiserror = "1.0.26"
