[package]
name = "freedroid"
version = "0.1.0"
authors = ["Edoardo Morandi <morandidodo@gmail.com>"]
edition = "2021"
license = "GPL-2.0-or-later"

[features]
arcade-input = []
gcw0 = []

[dependencies]
android_log-sys = "0.2.0"
array-init = "2.0.0"
bitflags = "1.3.2"
bstr = "0.2.17"
chrono = "0.4.19"
clap = { version = "3.0.5", features = ["derive", "cargo"] }
cstr = "0.2.5"
env_logger = "0.9.0"
libc = "0.2.112"
libc-extra = "0.3.2"
log = "0.4.14"
once_cell = "1.9.0"
rand = "0.8.4"
sdl = { path = "../sdl" }
sdl-sys = { path = "../sdl-sys" }

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.2.0"
